### ISSUE TITLE
Add New Code Portfolio [Hacktoberfest Special]

### ISSUE THREAD

**Issue by blackbird71SR** [blackbird71SR/Code-Portfolios#2]
- Create something different!
- Create a code portfolio using any programming language including HTML, CSS, Python, Java, C, C++ and many more
- You can even create a GUI and display your portfolio.

Possibilities are endless!

**Comment by Sirsha2468** [comment]
Can I contribute in this?

**Comment by prabhleenn** [comment]
please assign me this
